### ISSUE TITLE
Incomplete time calc can't be saved

### ISSUE THREAD

**Issue by friedger** [digitalkaoz/time-calc#48]
When I start to work I usually click start. When coming back to the page the start time is gone.

**Comment by digitalkaoz** [comment]
can you recheck this? i fixed a lot of thing recently

**Comment by friedger** [comment]
It is still not possible, because the "+" sign only appears when there is a end time
